# POTENSHEIA
<img width="600" align='left' src="https://user-images.githubusercontent.com/72685035/161909863-6cb34cad-b599-4e92-b0e4-a4a21c61df94.png">


**INTRODUCTION : Unleah your inner potential to a unicorn careerğŸ‘©â€ğŸ’»**


Right from childhood women face lots of struggles right from the time they are born, in rural areas people do not even consider educating or sending their daughters to higher studies, WHYYYYY???
See the potential every woman has in her, just be her support and witness the wonders she would do. 

â€œHumanâ€™s rights are women's rights and women's rights are humanâ€™s rightsâ€.Let's make this world a better and more equal place for every individual. 

